In [1]:
import os
import pandas as pd
from api_call import worldbank,consumer_electronics
import sys

In [2]:
#read both csvs
#if api fails, rely on backup CSV
try:
    worldbank_df = worldbank()
except:
    print("Oops!",sys.exc_info()[0],"occured, using CSV Instead")
    worldbank_df = pd.read_csv(os.path.join('Resources','worldbank.csv'))
try:
    CountryRevenueInfo = consumer_electronics()
except:
    print("Oops!",sys.exc_info()[0],"occured, using CSV Instead")
    CountryRevenueInfo = pd.read_csv(os.path.join('Resources','Consumer_Electronics_Sales.csv'))
    
worldhappiness_df = pd.read_csv(os.path.join('Resources', 'worldhappiness_prepped.csv'))

#join both data sources on Country Name, drop all rows that do not match

world_df = pd.merge(worldbank_df,worldhappiness_df, on='Country Code', how='outer')
world_df = pd.merge(world_df,CountryRevenueInfo, on='Country Code', how='outer')

In [ ]:
# len(world_df.groupby("Country"))
# len(worldhappiness_df.groupby('Country name'))
world_df.columns
# world_df[world_df['Country'].str.contains("Hong")]

In [4]:
world_df

,Country,Country Code,Region,Poverty Level,Capital City,Lat/Long,Country name,Year,Life Ladder,Log GDP per capita,...,"Most people can be trusted, WVS round 1981-1984","Most people can be trusted, WVS round 1989-1993","Most people can be trusted, WVS round 1994-1998","Most people can be trusted, WVS round 1999-2004","Most people can be trusted, WVS round 2005-2009","Most people can be trusted, WVS round 2010-2014",Country ID,Revenue 2019 ($M),Revenue 2017 ($M),Revenue 2018 ($M)
0,Aruba,AW,Latin America & Caribbean,High income,Oranjestad,"12.5167 , -70.0167",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,AF,South Asia,Low income,Kabul,"34.5228 , 69.1761",Afghanistan,2008.0,3.723590,7.168690,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afghanistan,AF,South Asia,Low income,Kabul,"34.5228 , 69.1761",Afghanistan,2009.0,4.401778,7.333790,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afghanistan,AF,South Asia,Low income,Kabul,"34.5228 , 69.1761",Afghanistan,2010.0,4.758381,7.386629,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afghanistan,AF,South Asia,Low income,Kabul,"34.5228 , 69.1761",Afghanistan,2011.0,3.831719,7.415019,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Afghanistan,AF,South Asia,Low income,Kabul,"34.5228 , 69.1761",Afghanistan,2012.0,3.782938,7.517126,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Afghanistan,AF,South Asia,Low income,Kabul,"34.5228 , 69.1761",Afghanistan,2013.0,3.572100,7.522238,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Afghanistan,AF,South Asia,Low income,Kabul,"34.5228 , 69.1761",Afghanistan,2014.0,3.130896,7.516955,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Afghanistan,AF,South Asia,Low income,Kabul,"34.5228 , 69.1761",Afghanistan,2015.0,3.982855,7.500539,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Afghanistan,AF,South Asia,Low income,Kabul,"34.5228 , 69.1761",Afghanistan,2016.0,4.220169,7.497038,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Afghanistan,AF,South Asia,Low income,Kabul,"34.5228 , 69.1761",Afghanistan,2017.0,2.661718,7.497755,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Afghanistan,AF,South Asia,Low income,Kabul,"34.5228 , 69.1761",Afghanistan,2018.0,2.694303,7.494588,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Angola,AO,Sub-Saharan Africa,Lower middle income,Luanda,"-8.81155 , 13.242",Angola,2011.0,5.589001,8.684613,...,NaN,NaN,NaN,NaN,NaN,NaN,163.0,153,101.617065052602,124.611435652634
13,Angola,AO,Sub-Saharan Africa,Lower middle income,Luanda,"-8.81155 , 13.242",Angola,2012.0,4.360250,8.699498,...,NaN,NaN,NaN,NaN,NaN,NaN,163.0,153,101.617065052602,124.611435652634
14,Angola,AO,Sub-Saharan Africa,Lower middle income,Luanda,"-8.81155 , 13.242",Angola,2013.0,3.937107,8.730368,...,NaN,NaN,NaN,NaN,NaN,NaN,163.0,153,101.617065052602,124.611435652634
15,Angola,AO,Sub-Saharan Africa,Lower middle income,Luanda,"-8.81155 , 13.242",Angola,2014.0,3.794838,8.741481,...,NaN,NaN,NaN,NaN,NaN,NaN,163.0,153,101.617065052602,124.611435652634
16,Albania,AL,Europe & Central Asia,Upper middle income,Tirane,"41.3317 , 19.8172",Albania,2007.0,4.634252,9.077331,...,NaN,NaN,0.243243,0.232000,NaN,NaN,355.0,44,39.245862158393,41.1632582672293
17,Albania,AL,Europe & Central Asia,Upper middle income,Tirane,"41.3317 , 19.8172",Albania,2009.0,5.485470,9.161638,...,NaN,NaN,0.243243,0.232000,NaN,NaN,355.0,44,39.245862158393,41.1632582672293
18,Albania,AL,Europe & Central Asia,Upper middle income,Tirane,"41.3317 , 19.8172",Albania,2010.0,5.268937,9.203032,...,NaN,NaN,0.243243,0.232000,NaN,NaN,355.0,44,39.245862158393,41.1632582672293
19,Albania,AL,Europe & Central Asia,Upper middle income,Tirane,"41.3317 , 19.8172",Albania,2011.0,5.867422,9.230904,...,NaN,NaN,0.243243,0.232000,NaN,NaN,355.0,44,39.245862158393,41.1632582672293
20,Albania,AL,Europe & Central Asia,Upper middle income,Tirane,"41.3317 , 19.8172",Albania,2012.0,5.510124,9.246655,...,NaN,NaN,0.243243,0.232000,NaN,NaN,355.0,44,39.245862158393,41.1632582672293
21,Albania,AL,Europe & Central Asia,Upper middle income,Tirane,"41.3317 , 19.8172",Albania,2013.0,4.550648,9.258445,...,NaN,NaN,0.243243,0.232000,NaN,NaN,355.0,44,39.245862158393,41.1632582672293
22,Albania,AL,Europe & Central Asia,Upper middle income,Tirane,"41.3317 , 19.8172",Albania,2014.0,4.813763,9.278104,...,NaN,NaN,0.243243,0.232000,NaN,NaN,355.0,44,39.245862158393,41.1632582672293
23,Albania,AL,Europe & Central Asia,Upper middle income,Tirane,"41.3317 , 19.8172",Albania,2015.0,4.606651,9.302960,...,NaN,NaN,0.243243,0.232000,NaN,NaN,355.0,44,39.245862158393,41.1632582672293
24,Albania,AL,Europe & Central Asia,Upper middle income,Tirane,"41.3317 , 19.8172",Albania,2016.0,4.511101,9.337532,...,NaN,NaN,0.243243,0.232000,NaN,NaN,355.0,44,39.245862158393,41.1632582672293
25,Albania,AL,Europe & Central Asia,Upper middle income,Tirane,"41.3317 , 19.8172",Albania,2017.0,4.639548,9.376145,...,NaN,NaN,0.243243,0.232000,NaN,NaN,355.0,44,39.245862158393,41.1632582672293
26,Albania,AL,Europe & Central Asia,Upper middle income,Tirane,"41.3317 , 19.8172",Albania,2018.0,5.004403,9.412399,...,NaN,NaN,0.243243,0.232000,NaN,NaN,355.0,44,39.245862158393,41.1632582672293
27,Andorra,AD,Europe & Central Asia,High income,Andorra la Vella,"42.5075 , 1.5218",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,United Arab Emirates,AE,Middle East & North Africa,High income,Abu Dhabi,"24.4764 , 54.3705",United Arab Emirates,2006.0,6.734222,11.386073,...,NaN,NaN,NaN,NaN,NaN,NaN,332.0,710,655.049306292644,679.969318961951
29,United Arab Emirates,AE,Middle East & North Africa,High income,Abu Dhabi,"24.4764 , 54.3705",United Arab Emirates,2009.0,6.866063,11.014850,...,NaN,NaN,NaN,NaN,NaN,NaN,332.0,710,655.049306292644,679.969318961951
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1730,South Africa,ZA,Sub-Saharan Africa,Upper middle income,Pretoria,"-25.746 , 28.1871",South Africa,2018.0,4.883922,9.411724,...,0.2903,0.282587,0.175729,0.115163,NaN,0.232812,112.0,764,654.311984137737,698.553505267318
1731,Zambia,ZM,Sub-Saharan Africa,Lower middle income,Lusaka,"-15.3982 , 28.2937",Zambia,2006.0,4.824455,7.866006,...,NaN,NaN,NaN,NaN,0.110429,NaN,353.0,29,21.7886839310709,24.8264204474652
1732,Zambia,ZM,Sub-Saharan Africa,Lower middle income,Lusaka,"-15.3982 , 28.2937",Zambia,2007.0,3.998293,7.918941,...,NaN,NaN,NaN,NaN,0.110429,NaN,353.0,29,21.7886839310709,24.8264204474652
1733,Zambia,ZM,Sub-Saharan Africa,Lower middle income,Lusaka,"-15.3982 , 28.2937",Zambia,2008.0,4.730263,7.966175,...,NaN,NaN,NaN,NaN,0.110429,NaN,353.0,29,21.7886839310709,24.8264204474652
1734,Zambia,ZM,Sub-Saharan Africa,Lower middle income,Lusaka,"-15.3982 , 28.2937",Zambia,2009.0,5.260361,8.026193,...,NaN,NaN,NaN,NaN,0.110429,NaN,353.0,29,21.7886839310709,24.8264204474652
1735,Zambia,ZM,Sub-Saharan Africa,Lower middle income,Lusaka,"-15.3982 , 28.2937",Zambia,2011.0,4.999114,8.120028,...,NaN,NaN,NaN,NaN,0.110429,NaN,353.0,29,21.7886839310709,24.8264204474652
1736,Zambia,ZM,Sub-Saharan Africa,Lower middle income,Lusaka,"-15.3982 , 28.2937",Zambia,2012.0,5.013375,8.163204,...,NaN,NaN,NaN,NaN,0.110429,NaN,353.0,29,21.7886839310709,24.8264204474652
1737,Zambia,ZM,Sub-Saharan Africa,Lower middle income,Lusaka,"-15.3982 , 28.2937",Zambia,2013.0,5.243996,8.182191,...,NaN,NaN,NaN,NaN,0.110429,NaN,353.0,29,21.7886839310709,24.8264204474652
1738,Zambia,ZM,Sub-Saharan Africa,Lower middle income,Lusaka,"-15.3982 , 28.2937",Zambia,2014.0,4.345837,8.197678,...,NaN,NaN,NaN,NaN,0.110429,NaN,353.0,29,21.7886839310709,24.8264204474652
1739,Zambia,ZM,Sub-Saharan Africa,Lower middle income,Lusaka,"-15.3982 , 28.2937",Zambia,2015.0,4.843164,8.196217,...,NaN,NaN,NaN,NaN,0.110429,NaN,353.0,29,21.7886839310709,24.8264204474652
1740,Zambia,ZM,Sub-Saharan Africa,Lower middle income,Lusaka,"-15.3982 , 28.2937",Zambia,2016.0,4.347544,8.203072,...,NaN,NaN,NaN,NaN,0.110429,NaN,353.0,29,21.7886839310709,24.8264204474652
1741,Zambia,ZM,Sub-Saharan Africa,Lower middle income,Lusaka,"-15.3982 , 28.2937",Zambia,2017.0,3.932777,8.213179,...,NaN,NaN,NaN,NaN,0.110429,NaN,353.0,29,21.7886839310709,24.8264204474652
1742,Zambia,ZM,Sub-Saharan Africa,Lower middle income,Lusaka,"-15.3982 , 28.2937",Zambia,2018.0,4.041488,8.223958,...,NaN,NaN,NaN,NaN,0.110429,NaN,353.0,29,21.7886839310709,24.8264204474652
1743,Zimbabwe,ZW,Sub-Saharan Africa,Lower middle income,Harare,"-17.8312 , 31.0672",Zimbabwe,2006.0,3.826268,7.366704,...,NaN,NaN,NaN,0.116683,NaN,0.082942,319.0,27,20.4384779236167,23.2114169968686
1744,Zimbabwe,ZW,Sub-Saharan Africa,Lower middle income,Harare,"-17.8312 , 31.0672",Zimbabwe,2007.0,3.280247,7.313939,...,NaN,NaN,NaN,0.116683,NaN,0.082942,319.0,27,20.4384779236167,23.2114169968686
1745,Zimbabwe,ZW,Sub-Saharan Africa,Lower middle income,Harare,"-17.8312 , 31.0672",Zimbabwe,2008.0,3.174264,7.102516,...,NaN,NaN,NaN,0.116683,NaN,0.082942,319.0,27,20.4384779236167,23.2114169968686
1746,Zimbabwe,ZW,Sub-Saharan Africa,Lower middle income,Harare,"-17.8312 , 31.0672",Zimbabwe,2009.0,4.055914,7.197595,...,NaN,NaN,NaN,0.116683,NaN,0.082942,319.0,27,20.4384779236167,23.2114169968686
1747,Zimbabwe,ZW,Sub-Saharan Africa,Lower middle income,Harare,"-17.8312 , 31.0672",Zimbabwe,2010.0,4.681570,7.296330,...,NaN,NaN,NaN,0.116683,NaN,0.082942,319.0,27,20.4384779236167,23.2114169968686
1748,Zimbabwe,ZW,Sub-Saharan Africa,Lower middle income,Harare,"-17.8312 , 31.0672",Zimbabwe,2011.0,4.845642,7.418864,...,NaN,NaN,NaN,0.116683,NaN,0.082942,319.0,27,20.4384779236167,23.2114169968686
1749,Zimbabwe,ZW,Sub-Saharan Africa,Lower middle income,Harare,"-17.8312 , 31.0672",Zimbabwe,2012.0,4.955101,7.534424,...,NaN,NaN,NaN,0.116683,NaN,0.082942,319.0,27,20.4384779236167,23.2114169968686
1750,Zimbabwe,ZW,Sub-Saharan Africa,Lower middle income,Harare,"-17.8312 , 31.0672",Zimbabwe,2013.0,4.690188,7.565154,...,NaN,NaN,NaN,0.116683,NaN,0.082942,319.0,27,20.4384779236167,23.2114169968686
1751,Zimbabwe,ZW,Sub-Saharan Africa,Lower middle income,Harare,"-17.8312 , 31.0672",Zimbabwe,2014.0,4.184451,7.562753,...,NaN,NaN,NaN,0.116683,NaN,0.082942,319.0,27,20.4384779236167,23.2114169968686
1752,Zimbabwe,ZW,Sub-Saharan Africa,Lower middle income,Harare,"-17.8312 , 31.0672",Zimbabwe,2015.0,3.703191,7.556052,...,NaN,NaN,NaN,0.116683,NaN,0.082942,319.0,27,20.4384779236167,23.2114169968686
1753,Zimbabwe,ZW,Sub-Saharan Africa,Lower middle income,Harare,"-17.8312 , 31.0672",Zimbabwe,2016.0,3.735400,7.538829,...,NaN,NaN,NaN,0.116683,NaN,0.082942,319.0,27,20.4384779236167,23.2114169968686
1754,Zimbabwe,ZW,Sub-Saharan Africa,Lower middle income,Harare,"-17.8312 , 31.0672",Zimbabwe,2017.0,3.638300,7.549491,...,NaN,NaN,NaN,0.116683,NaN,0.082942,319.0,27,20.4384779236167,23.2114169968686
1755,Zimbabwe,ZW,Sub-Saharan Africa,Lower middle income,Harare,"-17.8312 , 31.0672",Zimbabwe,2018.0,3.616480,7.553395,...,NaN,NaN,NaN,0.116683,NaN,0.082942,319.0,27,20.4384779236167,23.2114169968686
1756,NaN,NaN,NaN,NaN,NaN,NaN,Namibia,2007.0,4.885587,8.999317,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1757,NaN,NaN,NaN,NaN,NaN,NaN,Namibia,2014.0,4.573991,9.171329,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1758,NaN,NaN,NaN,NaN,NaN,NaN,Namibia,2017.0,4.441306,9.163439,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1759,NaN,NaN,NaN,NaN,NaN,NaN,Namibia,2018.0,4.834088,9.156214,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
world_df.to_csv(os.path.join("Resources",'almost_complete.csv'))

In [3]:
CountryRevenueInfo

,Country ID,Country Code,Revenue 2019 ($M),Revenue 2017 ($M),Revenue 2018 ($M)
South Africa,112,ZA,764,654.311984137737,698.553505267318
Morocco,159,MA,239,183.078812275335,206.378105759381
Nigeria,160,NG,788,482.544022601877,591.551699191516
Angola,163,AO,153,101.617065052602,124.611435652634
Botswana,175,BW,36,23.7766733261223,29.1041655104012
Burundi,183,BI,2,1.14278348430403,1.43811467196486
Cameroon,186,CM,94,36.3725869012952,64.6064766926061
Chad,191,TD,4,2.72909650935285,3.14283810098546
Republic of the Congo,199,CG,4,2.74889379414792,3.11779638754952
Benin,205,BJ,8,5.71910976183869,6.7870637919485
Equatorial Guinea,210,GQ,13,8.58049749358341,10.4416865439938
Ethiopia,211,ET,98,60.704140755028,76.464692922021
Gabon,222,GA,27,19.6557303905053,23.1081952086483
Gambia,224,GM,1,1.0891675864817,1.23815369958241
Ghana,226,GH,149,105.780004461378,124.661388694086
Guinea,234,GN,6,4.7590878326177,5.07665571781913
Ivory Coast,243,CI,123,90.2822519175198,104.119296032786
Kenya,247,KE,237,111.952408492034,146.647706908432
Lesotho,253,LS,5,4.34760483971605,4.81532366801101
Madagascar,259,MG,6,5.07228041285534,4.9443137861223
Malawi,260,MW,1,0.61724589545472,0.756876431029324
Mauritius,266,MU,42,32.8678205964302,37.0775968432967
Mozambique,273,MZ,15,10.8083559414494,12.6728442264373
Namibia,275,NA,35,22.4580880341958,28.6216300365044
Niger,286,NE,5,3.5248198448206,4.43104456984917
Rwanda,305,RW,12,8.63388678537258,10.2255943736855
Senegal,315,SN,30,20.5503991746085,24.6912729523056
Seychelles,316,SC,3,2.42923772179128,2.74105018243455
Sierra Leone,317,SL,4,2.76143763460667,3.15325223391318
Zimbabwe,319,ZW,27,20.4384779236167,23.2114169968686
...,...,...,...,...,...
Italy,141,IT,"3,692",2800.04701721162,3179.67708606777
Latvia,142,LV,89,75.1773609040505,80.5838556677773
Lithuania,143,LT,142,118.049908095164,127.812326947925
Netherlands,144,NL,"3,050",2599.05627550548,2784.88998245063
Norway,145,NO,"1,511",1345.70140972234,1414.45327143006
Poland,146,PL,"1,497",1151.76936296507,1295.81996015305
Portugal,147,PT,674,564.383256778661,609.574614413545
Romania,148,RO,656,560.958633974652,600.956697431887
Russia,149,RU,"3,179",2744.09244146683,2924.5118239987
Serbia,150,RS,126,104.485552242375,113.352151957041
Slovakia,151,SK,266,223.034039460059,240.722265185585
Slovenia,152,SI,123,108.097623497798,114.446452925318
Spain,153,ES,"4,407",3480.5242945698,3859.92087322038
Sweden,154,SE,"2,807",2477.95298419043,2614.34486979045
Switzerland,155,CH,"1,901",1719.1351471895,1795.72793523854
United Kingdom,156,GB,"12,075",10934.6209764776,11409.2227920167
Azerbaijan,165,AZ,128,117.161583166266,119.895970700203
Armenia,169,AM,32,34.2785689348695,31.3050881834641
Bosnia and Herzegovina,174,BA,55,48.571526305752,49.6967264505919
Belarus,184,BY,177,122.043397302983,148.086692535508
Cyprus,204,CY,76,61.8685028473866,68.2347999466834
Georgia,223,GE,35,40.881334697399,35.2147219985587
Iceland,240,IS,59,49.8846241955778,53.9084639187044
Luxembourg,257,LU,80,64.23297692425,70.3972822243398
Malta,263,MT,49,49.0514400176864,48.0673175650197
Moldova,269,MD,25,21.2159204934775,22.7271737788144
Montenegro,270,ME,16,12.6713830248352,13.8998294036948
Ukraine,338,UA,258,232.762890092133,237.667513524118
North Macedonia,339,MK,44,36.5670947899363,39.883557676855
Albania,355,AL,44,39.245862158393,41.1632582672293