In [1]:
import os
import pandas as pd
import sys
sys.path.insert(1, '../../notebooks/libs')
from api_call import worldbank,consumer_electronics

In [2]:
#read both csvs
#if api fails, rely on backup CSV
try:
    worldbank_df = worldbank()
except:
    print("Oops!",sys.exc_info()[0],"occured, using worldbank.csv instead")
    worldbank_df = pd.read_csv(os.path.join('worldbank.csv'))
try:
    CountryRevenueInfo = consumer_electronics()
except:
    print("Oops!",sys.exc_info()[0],"occured, using Consumer_Electronics_Sales.csv instead")
    CountryRevenueInfo = pd.read_csv(os.path.join('Consumer_Electronics_Sales.csv'))
    
worldhappiness_df = pd.read_csv(os.path.join('worldhappiness_prepped.csv'))

In [3]:
#join all data sources on Country Code, include all values regardless of match

world_df = pd.merge(worldbank_df,worldhappiness_df, on='Country Code', how='outer')
world_df = pd.merge(world_df,CountryRevenueInfo, on=['Country Code','Year'], how='outer')

In [4]:
# len(world_df.groupby("Country"))
# len(worldhappiness_df.groupby('Country name'))
world_df.columns
# world_df[world_df['Country'].str.contains("Hong")]

Index(['Country', 'Country Code', 'Region', 'Poverty Level', 'Capital City',
       'Lat/Long', 'Poverty Value (1-4)', 'Country name', 'Year',
       'Life Ladder', 'Log GDP per capita', 'Social support',
       'Healthy life expectancy at birth', 'Freedom to make life choices',
       'Generosity', 'Perceptions of corruption', 'Positive affect',
       'Negative affect', 'Confidence in national government',
       'Democratic Quality', 'Delivery Quality',
       'Standard deviation of ladder by country-year',
       'Standard deviation/Mean of ladder by country-year',
       'GINI index (World Bank estimate)',
       'GINI index (World Bank estimate), average 2000-16',
       'gini of household income reported in Gallup, by wp5-year',
       'Most people can be trusted, Gallup',
       'Most people can be trusted, WVS round 1981-1984',
       'Most people can be trusted, WVS round 1989-1993',
       'Most people can be trusted, WVS round 1994-1998',
       'Most people can be trusted, WVS round 1999-2004',
       'Most people can be trusted, WVS round 2005-2009',
       'Most people can be trusted, WVS round 2010-2014', 'Country ID',
       'Revenue ($M)'],
      dtype='object')

In [5]:
world_df

,Country,Country Code,Region,Poverty Level,Capital City,Lat/Long,Poverty Value (1-4),Country name,Year,Life Ladder,...,"gini of household income reported in Gallup, by wp5-year","Most people can be trusted, Gallup","Most people can be trusted, WVS round 1981-1984","Most people can be trusted, WVS round 1989-1993","Most people can be trusted, WVS round 1994-1998","Most people can be trusted, WVS round 1999-2004","Most people can be trusted, WVS round 2005-2009","Most people can be trusted, WVS round 2010-2014",Country ID,Revenue ($M)
0,Aruba,AW,Latin America & Caribbean,High income,Oranjestad,"12.5167 , -70.0167",4.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,AF,South Asia,Low income,Kabul,"34.5228 , 69.1761",1.0,Afghanistan,2008.0,3.723590,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afghanistan,AF,South Asia,Low income,Kabul,"34.5228 , 69.1761",1.0,Afghanistan,2009.0,4.401778,...,0.441906,0.286315,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afghanistan,AF,South Asia,Low income,Kabul,"34.5228 , 69.1761",1.0,Afghanistan,2010.0,4.758381,...,0.327318,0.275833,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afghanistan,AF,South Asia,Low income,Kabul,"34.5228 , 69.1761",1.0,Afghanistan,2011.0,3.831719,...,0.336764,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Afghanistan,AF,South Asia,Low income,Kabul,"34.5228 , 69.1761",1.0,Afghanistan,2012.0,3.782938,...,0.344540,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Afghanistan,AF,South Asia,Low income,Kabul,"34.5228 , 69.1761",1.0,Afghanistan,2013.0,3.572100,...,0.304368,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Afghanistan,AF,South Asia,Low income,Kabul,"34.5228 , 69.1761",1.0,Afghanistan,2014.0,3.130896,...,0.413974,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Afghanistan,AF,South Asia,Low income,Kabul,"34.5228 , 69.1761",1.0,Afghanistan,2015.0,3.982855,...,0.596918,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Afghanistan,AF,South Asia,Low income,Kabul,"34.5228 , 69.1761",1.0,Afghanistan,2016.0,4.220169,...,0.418629,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Afghanistan,AF,South Asia,Low income,Kabul,"34.5228 , 69.1761",1.0,Afghanistan,2017.0,2.661718,...,0.286599,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Afghanistan,AF,South Asia,Low income,Kabul,"34.5228 , 69.1761",1.0,Afghanistan,2018.0,2.694303,...,0.290681,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Afghanistan,AF,South Asia,Low income,Kabul,"34.5228 , 69.1761",1.0,Afghanistan,2019.0,3.203000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Angola,AO,Sub-Saharan Africa,Lower middle income,Luanda,"-8.81155 , 13.242",2.0,Angola,2011.0,5.589001,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Angola,AO,Sub-Saharan Africa,Lower middle income,Luanda,"-8.81155 , 13.242",2.0,Angola,2012.0,4.360250,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Angola,AO,Sub-Saharan Africa,Lower middle income,Luanda,"-8.81155 , 13.242",2.0,Angola,2013.0,3.937107,...,0.588065,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Angola,AO,Sub-Saharan Africa,Lower middle income,Luanda,"-8.81155 , 13.242",2.0,Angola,2014.0,3.794838,...,0.440699,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Albania,AL,Europe & Central Asia,Upper middle income,Tirane,"41.3317 , 19.8172",3.0,Albania,2007.0,4.634252,...,NaN,NaN,NaN,NaN,0.243243,0.232,NaN,NaN,NaN,NaN
18,Albania,AL,Europe & Central Asia,Upper middle income,Tirane,"41.3317 , 19.8172",3.0,Albania,2009.0,5.485470,...,0.617361,0.111004,NaN,NaN,0.243243,0.232,NaN,NaN,NaN,NaN
19,Albania,AL,Europe & Central Asia,Upper middle income,Tirane,"41.3317 , 19.8172",3.0,Albania,2010.0,5.268937,...,0.543528,0.201118,NaN,NaN,0.243243,0.232,NaN,NaN,NaN,NaN
20,Albania,AL,Europe & Central Asia,Upper middle income,Tirane,"41.3317 , 19.8172",3.0,Albania,2011.0,5.867422,...,0.407266,0.066618,NaN,NaN,0.243243,0.232,NaN,NaN,NaN,NaN
21,Albania,AL,Europe & Central Asia,Upper middle income,Tirane,"41.3317 , 19.8172",3.0,Albania,2012.0,5.510124,...,0.568153,NaN,NaN,NaN,0.243243,0.232,NaN,NaN,NaN,NaN
22,Albania,AL,Europe & Central Asia,Upper middle income,Tirane,"41.3317 , 19.8172",3.0,Albania,2013.0,4.550648,...,0.633796,NaN,NaN,NaN,0.243243,0.232,NaN,NaN,NaN,NaN
23,Albania,AL,Europe & Central Asia,Upper middle income,Tirane,"41.3317 , 19.8172",3.0,Albania,2014.0,4.813763,...,0.417219,NaN,NaN,NaN,0.243243,0.232,NaN,NaN,NaN,NaN
24,Albania,AL,Europe & Central Asia,Upper middle income,Tirane,"41.3317 , 19.8172",3.0,Albania,2015.0,4.606651,...,0.422627,NaN,NaN,NaN,0.243243,0.232,NaN,NaN,NaN,NaN
25,Albania,AL,Europe & Central Asia,Upper middle income,Tirane,"41.3317 , 19.8172",3.0,Albania,2016.0,4.511101,...,0.416540,NaN,NaN,NaN,0.243243,0.232,NaN,NaN,NaN,NaN
26,Albania,AL,Europe & Central Asia,Upper middle income,Tirane,"41.3317 , 19.8172",3.0,Albania,2017.0,4.639548,...,0.410488,NaN,NaN,NaN,0.243243,0.232,NaN,NaN,355.0,39.245862
27,Albania,AL,Europe & Central Asia,Upper middle income,Tirane,"41.3317 , 19.8172",3.0,Albania,2018.0,5.004403,...,0.456174,NaN,NaN,NaN,0.243243,0.232,NaN,NaN,355.0,41.163258
28,Albania,AL,Europe & Central Asia,Upper middle income,Tirane,"41.3317 , 19.8172",3.0,Albania,2019.0,4.719000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,355.0,44.000000
29,Andorra,AD,Europe & Central Asia,High income,Andorra la Vella,"42.5075 , 1.5218",4.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1946,NaN,SR,NaN,NaN,NaN,NaN,NaN,NaN,2018.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,323.0,2.581615
1947,NaN,HK,NaN,NaN,NaN,NaN,NaN,NaN,2018.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,118.0,881.363683
1948,NaN,BH,NaN,NaN,NaN,NaN,NaN,NaN,2018.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,167.0,112.741531
1949,NaN,BT,NaN,NaN,NaN,NaN,NaN,NaN,2018.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,172.0,3.276527
1950,NaN,BN,NaN,NaN,NaN,NaN,NaN,NaN,2018.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,181.0,9.729525
1951,NaN,IQ,NaN,NaN,NaN,NaN,NaN,NaN,2018.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,242.0,416.819048
1952,NaN,KW,NaN,NaN,NaN,NaN,NaN,NaN,2018.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,249.0,235.144146
1953,NaN,OM,NaN,NaN,NaN,NaN,NaN,NaN,2018.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,274.0,104.506229
1954,NaN,TL,NaN,NaN,NaN,NaN,NaN,NaN,2018.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,301.0,2.221970
1955,NaN,QA,NaN,NaN,NaN,NaN,NaN,NaN,2018.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,303.0,255.549477
1956,NaN,TJ,NaN,NaN,NaN,NaN,NaN,NaN,2018.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,327.0,8.506390
1957,NaN,FJ,NaN,NaN,NaN,NaN,NaN,NaN,2018.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,216.0,10.720385
1958,NaN,PG,NaN,NaN,NaN,NaN,NaN,NaN,2018.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,296.0,5.745632
1959,NaN,HU,NaN,NaN,NaN,NaN,NaN,NaN,2018.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,139.0,353.265522
1960,NaN,PL,NaN,NaN,NaN,NaN,NaN,NaN,2018.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,146.0,1295.819960
1961,NaN,IS,NaN,NaN,NaN,NaN,NaN,NaN,2018.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,240.0,53.908464
1962,NaN,AO,NaN,NaN,NaN,NaN,NaN,NaN,2019.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,163.0,153.000000
1963,NaN,GQ,NaN,NaN,NaN,NaN,NaN,NaN,2019.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,210.0,13.000000
1964,NaN,NA,NaN,NaN,NaN,NaN,NaN,NaN,2019.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,275.0,35.000000
1965,NaN,SC,NaN,NaN,NaN,NaN,NaN,NaN,2019.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,316.0,3.000000
1966,NaN,SD,NaN,NaN,NaN,NaN,NaN,NaN,2019.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,322.0,86.000000
1967,NaN,BZ,NaN,NaN,NaN,NaN,NaN,NaN,2019.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,177.0,6.000000
1968,NaN,CU,NaN,NaN,NaN,NaN,NaN,NaN,2019.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,203.0,172.000000
1969,NaN,GY,NaN,NaN,NaN,NaN,NaN,NaN,2019.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,235.0,4.000000
1970,NaN,SR,NaN,NaN,NaN,NaN,NaN,NaN,2019.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,323.0,3.000000
1971,NaN,BN,NaN,NaN,NaN,NaN,NaN,NaN,2019.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,181.0,12.000000
1972,NaN,OM,NaN,NaN,NaN,NaN,NaN,NaN,2019.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,274.0,108.000000
1973,NaN,TL,NaN,NaN,NaN,NaN,NaN,NaN,2019.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,301.0,3.000000
1974,NaN,FJ,NaN,NaN,NaN,NaN,NaN,NaN,2019.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,216.0,12.000000
1975,NaN,PG,NaN,NaN,NaN,NaN,NaN,NaN,2019.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,296.0,7.000000

In [8]:
world_df.to_csv(os.path.join("..","cleanData",'almost_complete.csv'),index=False)

In [7]:
CountryRevenueInfo

                       Country Code  Country ID  Revenue ($M)    Year
South Africa                     ZA         112    654.311984  2017.0
Morocco                          MA         159    183.078812  2017.0
Nigeria                          NG         160    482.544023  2017.0
Angola                           AO         163    101.617065  2017.0
Botswana                         BW         175     23.776673  2017.0
Burundi                          BI         183      1.142783  2017.0
Cameroon                         CM         186     36.372587  2017.0
Chad                             TD         191      2.729097  2017.0
Republic of the Congo            CG         199      2.748894  2017.0
Benin                            BJ         205      5.719110  2017.0
Equatorial Guinea                GQ         210      8.580497  2017.0
Ethiopia                         ET         211     60.704141  2017.0
Gabon                            GA         222     19.655730  2017.0
Gambia                           GM         224      1.089168  2017.0
Ghana                            GH         226    105.780004  2017.0
Guinea                           GN         234      4.759088  2017.0
Ivory Coast                      CI         243     90.282252  2017.0
Kenya                            KE         247    111.952408  2017.0
Lesotho                          LS         253      4.347605  2017.0
Madagascar                       MG         259      5.072280  2017.0
Malawi                           MW         260      0.617246  2017.0
Mauritius                        MU         266     32.867821  2017.0
Mozambique                       MZ         273     10.808356  2017.0
Namibia                          NA         275     22.458088  2017.0
Niger                            NE         286      3.524820  2017.0
Rwanda                           RW         305      8.633887  2017.0
Senegal                          SN         315     20.550399  2017.0
Seychelles                       SC         316      2.429238  2017.0
Sierra Leone                     SL         317      2.761438  2017.0
Zimbabwe                         ZW         319     20.438478  2017.0
...                             ...         ...           ...     ...
Italy                            IT         141   3692.000000  2019.0
Latvia                           LV         142     89.000000  2019.0
Lithuania                        LT         143    142.000000  2019.0
Netherlands                      NL         144   3050.000000  2019.0
Norway                           NO         145   1511.000000  2019.0
Poland                           PL         146   1497.000000  2019.0
Portugal                         PT         147    674.000000  2019.0
Romania                          RO         148    656.000000  2019.0
Russia                           RU         149   3179.000000  2019.0
Serbia                           RS         150    126.000000  2019.0
Slovakia                         SK         151    266.000000  2019.0
Slovenia                         SI         152    123.000000  2019.0
Spain                            ES         153   4407.000000  2019.0
Sweden                           SE         154   2807.000000  2019.0
Switzerland                      CH         155   1901.000000  2019.0
United Kingdom                   GB         156  12075.000000  2019.0
Azerbaijan                       AZ         165    128.000000  2019.0
Armenia                          AM         169     32.000000  2019.0
Bosnia and Herzegovina           BA         174     55.000000  2019.0
Belarus                          BY         184    177.000000  2019.0
Cyprus                           CY         204     76.000000  2019.0
Georgia                          GE         223     35.000000  2019.0
Iceland                          IS         240     59.000000  2019.0
Luxembourg                       LU         257     80.000000  2019.0
Malta                            MT         263     49.000000  2019.0
Moldova                          MD         269     25.000000  2019.0
Montenegro                       ME         270     16.000000  2019.0
Ukraine                          UA         338    258.000000  2019.0
North Macedonia                  MK         339     44.000000  2019.0
Albania                          AL         355     44.000000  2019.0

[450 rows x 4 columns]